### PR TITLE
adds for_each page

### LINKED ISSUE #14: Create a page on `for_each`
Describe the use of the [`for_each`](https://www.terraform.io/language/meta-arguments/for_each) argument on a dedicated page.

### PR DESCRIPTION
**Pull request by RafaelReia**
Closes #14

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Hi @RafaelReia, thanks for your contribution - I'll take a look at this today!

**Comment by RafaelReia** [comment]
@bschaatsbergen I made a commit with changes to fix the whitespaces and the trailing spaces issues

**Review by bschaatsbergen — APPROVED** [review]
LGTM 🚀

**Comment by bschaatsbergen** [comment]
Thanks a lot for your contribution @RafaelReia, it's very much appreciated!

**Comment by bschaatsbergen** [comment]
Released under `v0.1.19`

**Pull request merged**
